"""
Apply JPL Horizons orbital elements to frontend/src/lib/famous_neos.ts.

Reads reports/jpl-patches.txt (generated by verify_jpl_orbital_elements.py)
and replaces each matching `orbit: { ... }` block plus appends
`orbital_epoch_jd`, `data_source`, `last_verified_date` fields.

Run only after verify_jpl_orbital_elements.py has produced a clean fetch.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


def main() -> int:
    repo = Path(__file__).resolve().parent.parent
    ts_path = repo / "frontend/src/lib/famous_neos.ts"
    patches_path = repo / "reports/jpl-patches.txt"

    text = ts_path.read_text()
    patches_text = patches_path.read_text()

    patch_blocks = {}
    entries = re.split(r"//\s+", patches_text)
    for entry in entries:
        entry = entry.strip()
        if not entry:
            continue
        first_nl = entry.find("\n")
        name = entry[:first_nl].strip()
        body = entry[first_nl + 1:].strip()
        if not body:
            continue
        patch_blocks[name] = body

    print(f"Loaded {len(patch_blocks)} patch blocks.", file=sys.stderr)

    # Extract J2000 constants for metadata fields
    epoch_jd = 2451545.0
    verified_date = "2026-04-24"
    data_source = "JPL Horizons (ssd.jpl.nasa.gov/api/horizons.api) ELEMENTS @500@10"

    replaced = 0
    # For each named object in catalog, replace its `orbit:` block with the
    # patch version, then insert the three provenance fields right after it.
    for name, patch in patch_blocks.items():
        # Escape for regex use
        name_re = re.escape(name)
        # Match entry shape: name: "XYZ", ... orbit: { ... },
        # We only need to find the orbit block between that name marker and the
        # next top-level field. We anchor on `name: "<name>"`.
        pattern = re.compile(
            rf'(name:\s*"{name_re}",.*?)(orbit:\s*\{{[^{{}}]*\}},?)',
            re.DOTALL,
        )
        m = pattern.search(text)
        if not m:
            print(f"[WARN] Could not locate orbit block for {name}", file=sys.stderr)
            continue

        # The patch starts with `    orbit: {` and ends with `},  // JPL...`
        provenance = (
            f'\n    orbital_epoch_jd: {epoch_jd},\n'
            f'    data_source: "{data_source}",\n'
            f'    last_verified_date: "{verified_date}",'
        )
        new_block = patch + provenance
        text = text[: m.start(2)] + new_block + text[m.end(2):]
        replaced += 1

    print(f"Replaced {replaced} orbit blocks.", file=sys.stderr)

    ts_path.write_text(text)
    print(f"Wrote {ts_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
