"""
Apply JPL Horizons orbital elements to frontend/src/lib/famous_neos.ts.

Reads reports/jpl-patches.txt (generated by verify_jpl_orbital_elements.py)
and rewrites, for each matching `name:` entry:

  * the `orbit: { ... }` block (with new mean_anomaly_deg_epoch etc.)
  * the `orbital_epoch_jd`, `data_source`, `last_verified_date` provenance
    fields (updated in place if present, inserted after `orbit:` if missing).

The epoch JD + fetch date are extracted from the trailing comment that
verify_jpl_orbital_elements.py writes on each patch block:

    },  // JPL Horizons @ JD 2461155.0, fetched 2026-04-24

Run only after verify_jpl_orbital_elements.py has produced a clean fetch.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


PROVENANCE_PATTERN = re.compile(
    r"(?:\n\s*orbital_epoch_jd:\s*[-+0-9.eE]+,)?"
    r"(?:\n\s*data_source:\s*\"[^\"]*\",)?"
    r"(?:\n\s*last_verified_date:\s*\"[^\"]*\",)?"
)

EPOCH_COMMENT_PATTERN = re.compile(
    r"//\s*JPL\s+Horizons\s*@\s*JD\s*([-+0-9.eE]+)\s*,\s*fetched\s*([0-9]{4}-[0-9]{2}-[0-9]{2})"
)


def main() -> int:
    repo = Path(__file__).resolve().parent.parent
    ts_path = repo / "frontend/src/lib/famous_neos.ts"
    patches_path = repo / "reports/jpl-patches.txt"

    text = ts_path.read_text()
    patches_text = patches_path.read_text()

    # reports/jpl-patches.txt is a stream of "// Name\n<orbit block>\n" records
    # separated by blank lines. Split on "// " at line start.
    patch_blocks: dict[str, tuple[str, float, str]] = {}  # name -> (body, epoch_jd, fetched_date)
    entries = re.split(r"\n(?=//\s+\S)", patches_text.strip())
    for entry in entries:
        entry = entry.strip()
        if not entry.startswith("//"):
            continue
        first_nl = entry.find("\n")
        name = entry[3:first_nl].strip()  # skip leading "// "
        body = entry[first_nl + 1:].strip()
        if not body:
            continue
        m = EPOCH_COMMENT_PATTERN.search(body)
        if not m:
            print(f"[WARN] patch for {name} missing epoch comment — skipping",
                  file=sys.stderr)
            continue
        epoch_jd = float(m.group(1))
        fetched_date = m.group(2)
        patch_blocks[name] = (body, epoch_jd, fetched_date)

    print(f"Loaded {len(patch_blocks)} patch blocks.", file=sys.stderr)

    data_source = "JPL Horizons (ssd.jpl.nasa.gov/api/horizons.api) ELEMENTS @500@10"
    replaced = 0
    for name, (patch_body, epoch_jd, fetched_date) in patch_blocks.items():
        name_re = re.escape(name)
        # Match: name: "XYZ", ... orbit: { ... }, [optional provenance block]
        pattern = re.compile(
            rf'(name:\s*"{name_re}",.*?)'
            rf'(orbit:\s*\{{[^{{}}]*\}},[^\n]*(?:\n\s*orbital_epoch_jd:[^\n]*)?'
            rf'(?:\n\s*data_source:[^\n]*)?'
            rf'(?:\n\s*last_verified_date:[^\n]*)?)',
            re.DOTALL,
        )
        m = pattern.search(text)
        if not m:
            print(f"[WARN] Could not locate orbit/provenance block for {name}",
                  file=sys.stderr)
            continue

        provenance = (
            f"\n    orbital_epoch_jd: {epoch_jd},"
            f"\n    data_source: \"{data_source}\","
            f"\n    last_verified_date: \"{fetched_date}\","
        )
        new_block = patch_body + provenance
        text = text[: m.start(2)] + new_block + text[m.end(2):]
        replaced += 1

    print(f"Replaced {replaced} orbit blocks.", file=sys.stderr)
    ts_path.write_text(text)
    print(f"Wrote {ts_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
